// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/cart.tsx";
import * as $4 from "./routes/catalogue.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/payment.tsx";
import * as $7 from "./routes/products/bestsellers/[Al_3].tsx";
import * as $8 from "./routes/products/catalogue/[Al_1].tsx";
import * as $9 from "./routes/products/new/[Al_4].tsx";
import * as $10 from "./routes/products/womencloth/[Al_2].tsx";
import * as $11 from "./routes/shipping.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ImageSlider.tsx";
import * as $$2 from "./islands/Navbar.tsx";
import * as $$3 from "./islands/Product.tsx";
import * as $$4 from "./islands/Section_bar.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/cart.tsx": $3,
    "./routes/catalogue.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/payment.tsx": $6,
    "./routes/products/bestsellers/[Al_3].tsx": $7,
    "./routes/products/catalogue/[Al_1].tsx": $8,
    "./routes/products/new/[Al_4].tsx": $9,
    "./routes/products/womencloth/[Al_2].tsx": $10,
    "./routes/shipping.tsx": $11,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ImageSlider.tsx": $$1,
    "./islands/Navbar.tsx": $$2,
    "./islands/Product.tsx": $$3,
    "./islands/Section_bar.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
