export const All_items_data = [
  {
    name: "Stylish",
    price: "50 USD",
    image: "/images/catalogue_list/1.png",
    description: "Life is great",
    address: "/products/catalogue/0",
  },
  {
    name: "Dress",
    price: "50 USD",
    image: "/images/catalogue_list/2.png",
    description: "Life is great",
    address: "/products/catalogue/1",
  },
  {
    name: "Nightwear",
    price: "50 USD",
    image: "/images/catalogue_list/3.png",
    description: "Life is great",
    address: "/products/catalogue/2",
  },
  {
    name: "Bow-Style",
    price: "50 USD",
    image: "/images/catalogue_list/4.png",
    description: "Life is great",
    address: "/products/catalogue/3",
  },
  {
    name: "Black-Tee",
    price: "50 USD",
    image: "/images/catalogue_list/5.png",
    description: "Life is great",
    address: "/products/catalogue/4",
  },
  {
    name: "Shorts&Top",
    price: "50 USD",
    image: "/images/catalogue_list/6.png",
    description: "Life is great",
    address: "/products/catalogue/5",
  },
  {
    name: "Crop-Top&Jeans",
    price: "50 USD",
    image: "/images/catalogue_list/7.png",
    description: "Life is great",
    address: "/products/catalogue/6",
  },
  {
    name: "White-Tee",
    price: "50 USD",
    image: "/images/catalogue_list/8.png",
    description: "Life is great",
    address: "/products/catalogue/7",
  },
  {
    name: "Jeans",
    price: "50 USD",
    image: "/images/catalogue_list/9.png",
    description: "Life is great",
    address: "/products/catalogue/8",
  },
  {
    name: "Royal-Scarf",
    price: "50 USD",
    image: "/images/catalogue_list/10.png",
    description: "Life is great",
    address: "/products/catalogue/9",
  },
  {
    name: "Summer-Wear",
    price: "50 USD",
    image: "/images/catalogue_list/11.png",
    description: "Life is great",
    address: "/products/catalogue/10",
  },
  {
    name: "Urban-Rock",
    price: "50 USD",
    image: "/images/catalogue_list/12.png",
    description: "Life is great",
    address: "/products/catalogue/11",
  },
];
