export const All_items_data = [
  { name:"Stylish",
    price:"50 USD",
    image: "/images/catalogue_list/1.png", 
    description:"Life is great",
    address: "/",
},
  { name:"Dress",
    price:"50 USD",
    image: "/images/catalogue_list/2.png",
    description:"Life is great",
    address: "/",
},
  { name:"Nightwear",
    price:"50 USD",
    image: "/images/catalogue_list/3.png",
    description:"Life is great",
    address: "/",
},
  { name:"Bow-Style",
    price:"50 USD",
    image: "/images/catalogue_list/4.png",
    description:"Life is great",
    address: "/",
},
  { name:"Black-Tee",
    price:"50 USD",
    image: "/images/catalogue_list/5.png",
    description:"Life is great",
    address: "/",
},
  { name:"Shorts&Top",
    price:"50 USD",
    image: "/images/catalogue_list/6.png",
    description:"Life is great",
    address: "/",
},
  { name:"Crop-Top&Jeans",
    price:"50 USD",
    image: "/images/catalogue_list/7.png",
    description:"Life is great",
    address: "/",
},
  { name:"White-Tee",
    price:"50 USD",
    image: "/images/catalogue_list/8.png",
    description:"Life is great",
    address: "/",
},
  { name:"Jeans",
    price:"50 USD",
    image: "/images/catalogue_list/9.png",
    description:"Life is great",
    address: "/",
},
  { name:"Royal-Scarf",
    price:"50 USD",
    image: "/images/catalogue_list/10.png",
    description:"Life is great",
    address: "/",
},
  { name:"Summer-Wear",
    price:"50 USD",
    image: "/images/catalogue_list/11.png",  
  description:"Life is great",
    address: "/",
},
  { name:"Urban-Rock",
    price:"50 USD",
    image: "/images/catalogue_list/12.png",
    description:"Life is great",
    address: "/",
},
];
