export const NewData=[
    {
        image:"/images/new-1.png",
        address:"/products/new/0"
    },
    {
        image:"/images/new-2.png",
        address:"/products/new/1"
    },
    {
        image:"/images/new-3.png",
        address:"/products/new/2"
    },
    {
        image:"/images/new-4.png",
        address:"/products/new/3"
    },
    {
        image:"/images/new-5.png",
        address:"/products/new/4"
    },
    {
        image:"/images/new-6.png",
        address:"/products/new/5"
    },
    {
        image:"/images/new-7.png",
        address:"/products/new/6"
    },
    {
        image:"/images/new-8.png",
        address:"/products/new/7"
    }
]